name: 'beejanRide'
version: '1.0.0'

profile: 'beejanRide'

# File path configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  beejanRide:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']

    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['intermediate']

    mart:
      core:
        +materialized: table
        +schema: core
        +tags: ['core']

      finance:
        +materialized: table
        +schema: finance
        +tags: ['finance']

      operations:
        +materialized: table
        +schema: operations
        +tags: ['operations']

      fraud:
        +materialized: table
        +schema: fraud
        +tags: ['fraud']


snapshots:
  beejanRide:
    +target_schema: snapshots
    +strategy: timestamp
    +invalidate_hard_deletes: true

seeds:
  beejanRide:
    +schema: seeds

flags:
  bigquery_use_batch_source_freshness: true